/**
 * Core puzzle output generated by the system.
 *
 * The generator should always produce puzzles in this format.
 *
 * This structure intentionally separates:
 *
 * - puzzle logic
 * - clues
 * - interaction interface
 * - failure mechanics
 * - hint ladder
 *
 * so that puzzles remain understandable and extensible.
 */

export type PuzzleDifficulty = "easy" | "medium" | "hard";

export type GeneratedPuzzle = {
  id: string;

  difficulty: PuzzleDifficulty;

  environment?: string;

  archetype: string;

  tags: string[];

  interface: PuzzleInterface;

  solution: PuzzleSolution;

  clues: PuzzleClue[];

  twist?: PuzzleTwist;

  consequence: PuzzleConsequence;

  feedback: PuzzleFeedback;

  hints: string[];

  validation: PuzzleValidation;

  gmNotes: PuzzleGMNotes;
};

export type PuzzleInterface = {
  primary: string[];
  secondary?: string[];
};

export type PuzzleSolution = {
  objective: string;

  steps: string[];

  finalState: string;

  internalLogic: string;
};

export type PuzzleClue = {
  source: string;

  content: string;

  directness: "direct" | "partial" | "indirect";

  pointsTo: string[];
};

export type PuzzleTwist = {
  type: string;

  effect: string;
};

export type PuzzleConsequence = {
  type: string;

  severity: "low" | "medium" | "high";

  behavior: string;
};

export type PuzzleFeedback = {
  successSignals: string[];

  failureSignals: string[];

  partialProgressSignals: string[];
};

export type PuzzleValidation = {
  isSolvable: boolean;

  clueCoverage: number;

  contradictionWarnings: string[];
};

export type PuzzleGMNotes = {
  likelyMisreads: string[];

  bypassIdeas: string[];

  pacingAdvice: string;
};